version: 2
updates:
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: gradle
    rebase-strategy: auto
    schedule:
      interval: weekly
    groups:
      kotlin-plugins:
        patterns:
          - "jvm"
          - "plugin.spring"
          - "plugin.jpa"
  - directory: /
    package-ecosystem: docker
    rebase-strategy: auto
    schedule:
      interval: weekly
  - directory: /
    package-ecosystem: github-actions
    rebase-strategy: auto
    schedule:
      interval: weekly
